### ISSUE TITLE
Question about using `PDALGetPackedPoint` and configuring `dims` parameter.

### ISSUE THREAD

**Issue by metasim** [PDAL/CAPI#20]
_Not sure if this is a feature request, or me not understanding the API._ :) 

The signature of `PDALGetPackedPoint` is:

    size_t PDALGetPackedPoint(PDALPointViewPtr view, PDALDimTypeListPtr dims, PDALPointId idx, char *buffer);

Intuitively I'd assume I could specify a subset of available dimensions through `dims`, (i.e. if I only want "X", "Y", & "Z"). However, I'm not seeing any means of constructing a `PDALDimTypeList` except from `PDALGetPointLayoutDimTypes`. 

Is this function only intended to provide a "packed point" with all dimensions in the layout, or am I misunderstanding how one uses `PDALDimTypeList`? Thanks!

**Comment by runette** [comment]
Sorry about the slow reply - holidays :)

I think this is a misunderstanding of the various APIs. Some of this may be obvious - so apologies for that in advance ..

- the C API wraps the PDAL cpp API - so the way it works is defined in that repository, however
- the C++ API allows access to the memory object that is the result of a PDAL pipeline process, so
- neither API can actually define what dimensions are in the memory object - they just receive the definition from PDAL core and use that to work out where to find the data that you want!
- if you want to limit the dimensions in the memory object - you have to do that in the PDAL pipeline process itself (i.e. in the stages defined or in the JSON).

That is why `PDALDimTypeList` is effectively read-only

**Comment by metasim** [comment]
@runette Thank you for the reply... this is *extremely* helpful information. I didn't realize this was also a constraint on the C++ side as well. I am working on [Rust bindings to PDAL](https://github.com/georust/pdal) and knowing this will save me from a big ol' rabbit hole! 🖖

**Comment by runette** [comment]
@metasim Yeah - it is more a conceptual architectural constraint in PDAL core. PDAL runs a series of stages (that can include loading from file and saving to file) passing the data between stages as in-memory pointviews and finally (if accessed through an API) passing the pointer(s) to the pointview(s) to the API.

The C API takes a fairly low-level approach - i.e. it basically makes this cpp API accessible in C, since it is mainly to be used by other bindings - C being being simpler for interop than cpp. 

What the Python bindings do is take the pointview and copy it into a Numpy object so that the powerful manipulation tools in Numpy can be used natively to select the dimensions. The C# / Unity bindings that I maintain do something similar. You should probably do something similar in Rust.
